var Parser = require('../lib/parser/hiredis'***REMOVED***.Parser;
var assert = require('assert'***REMOVED***;

/*
This test makes sure that exceptions thrown inside of "reply" event handlers
are not trapped and mistakenly emitted as parse errors.
*/
(function testExecuteDoesNotCatchReplyCallbackExceptions(***REMOVED*** {
  var parser = new Parser(***REMOVED***;
  var replies = [{}];

  parser.reader = {
    feed: function(***REMOVED*** {},
    get: function(***REMOVED*** {
      return replies.shift(***REMOVED***;
  ***REMOVED***
***REMOVED***;

  var emittedError = false;
  var caughtException = false;

  parser
    .on('error', function(***REMOVED*** {
      emittedError = true;
  ***REMOVED******REMOVED***
    .on('reply', function(***REMOVED*** {
      throw new Error('bad'***REMOVED***;
  ***REMOVED******REMOVED***;

  try {
    parser.execute(***REMOVED***;
***REMOVED*** catch (err***REMOVED*** {
    caughtException = true;
***REMOVED***

  assert.equal(caughtException, true***REMOVED***;
  assert.equal(emittedError, false***REMOVED***;
}***REMOVED***(***REMOVED***;
